// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ijufumi/practice-202512/app/domain/models"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Create(db *gorm.DB, client *models.Client) error {
	ret := _mock.Called(db, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *models.Client) error); ok {
		r0 = returnFunc(db, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - client *models.Client
func (_e *MockClientRepository_Expecter) Create(db interface{}, client interface{}) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", db, client)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(db *gorm.DB, client *models.Client)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *models.Client
		if args[1] != nil {
			arg1 = args[1].(*models.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(err error) *MockClientRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(db *gorm.DB, client *models.Client) error) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) FindByID(db *gorm.DB, id string) (*models.Client, error) {
	ret := _mock.Called(db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) (*models.Client, error)); ok {
		return returnFunc(db, id)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) *models.Client); ok {
		r0 = returnFunc(db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = returnFunc(db, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockClientRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - db *gorm.DB
//   - id string
func (_e *MockClientRepository_Expecter) FindByID(db interface{}, id interface{}) *MockClientRepository_FindByID_Call {
	return &MockClientRepository_FindByID_Call{Call: _e.mock.On("FindByID", db, id)}
}

func (_c *MockClientRepository_FindByID_Call) Run(run func(db *gorm.DB, id string)) *MockClientRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_FindByID_Call) Return(client *models.Client, err error) *MockClientRepository_FindByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientRepository_FindByID_Call) RunAndReturn(run func(db *gorm.DB, id string) (*models.Client, error)) *MockClientRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
