// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ijufumi/practice-202512/app/domain/models"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockClientBankAccountRepository creates a new instance of MockClientBankAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientBankAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientBankAccountRepository {
	mock := &MockClientBankAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientBankAccountRepository is an autogenerated mock type for the ClientBankAccountRepository type
type MockClientBankAccountRepository struct {
	mock.Mock
}

type MockClientBankAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientBankAccountRepository) EXPECT() *MockClientBankAccountRepository_Expecter {
	return &MockClientBankAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientBankAccountRepository
func (_mock *MockClientBankAccountRepository) Create(db *gorm.DB, account *models.ClientBankAccount) error {
	ret := _mock.Called(db, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *models.ClientBankAccount) error); ok {
		r0 = returnFunc(db, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientBankAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientBankAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - account *models.ClientBankAccount
func (_e *MockClientBankAccountRepository_Expecter) Create(db interface{}, account interface{}) *MockClientBankAccountRepository_Create_Call {
	return &MockClientBankAccountRepository_Create_Call{Call: _e.mock.On("Create", db, account)}
}

func (_c *MockClientBankAccountRepository_Create_Call) Run(run func(db *gorm.DB, account *models.ClientBankAccount)) *MockClientBankAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *models.ClientBankAccount
		if args[1] != nil {
			arg1 = args[1].(*models.ClientBankAccount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientBankAccountRepository_Create_Call) Return(err error) *MockClientBankAccountRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientBankAccountRepository_Create_Call) RunAndReturn(run func(db *gorm.DB, account *models.ClientBankAccount) error) *MockClientBankAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockClientBankAccountRepository
func (_mock *MockClientBankAccountRepository) FindByID(db *gorm.DB, id string) (*models.ClientBankAccount, error) {
	ret := _mock.Called(db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.ClientBankAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) (*models.ClientBankAccount, error)); ok {
		return returnFunc(db, id)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) *models.ClientBankAccount); ok {
		r0 = returnFunc(db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ClientBankAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = returnFunc(db, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientBankAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockClientBankAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - db *gorm.DB
//   - id string
func (_e *MockClientBankAccountRepository_Expecter) FindByID(db interface{}, id interface{}) *MockClientBankAccountRepository_FindByID_Call {
	return &MockClientBankAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", db, id)}
}

func (_c *MockClientBankAccountRepository_FindByID_Call) Run(run func(db *gorm.DB, id string)) *MockClientBankAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientBankAccountRepository_FindByID_Call) Return(clientBankAccount *models.ClientBankAccount, err error) *MockClientBankAccountRepository_FindByID_Call {
	_c.Call.Return(clientBankAccount, err)
	return _c
}

func (_c *MockClientBankAccountRepository_FindByID_Call) RunAndReturn(run func(db *gorm.DB, id string) (*models.ClientBankAccount, error)) *MockClientBankAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
