// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ijufumi/practice-202512/app/domain/models"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockCompanyRepository creates a new instance of MockCompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompanyRepository {
	mock := &MockCompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompanyRepository is an autogenerated mock type for the CompanyRepository type
type MockCompanyRepository struct {
	mock.Mock
}

type MockCompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompanyRepository) EXPECT() *MockCompanyRepository_Expecter {
	return &MockCompanyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCompanyRepository
func (_mock *MockCompanyRepository) Create(db *gorm.DB, company *models.Company) error {
	ret := _mock.Called(db, company)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *models.Company) error); ok {
		r0 = returnFunc(db, company)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompanyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCompanyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - company *models.Company
func (_e *MockCompanyRepository_Expecter) Create(db interface{}, company interface{}) *MockCompanyRepository_Create_Call {
	return &MockCompanyRepository_Create_Call{Call: _e.mock.On("Create", db, company)}
}

func (_c *MockCompanyRepository_Create_Call) Run(run func(db *gorm.DB, company *models.Company)) *MockCompanyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *models.Company
		if args[1] != nil {
			arg1 = args[1].(*models.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyRepository_Create_Call) Return(err error) *MockCompanyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompanyRepository_Create_Call) RunAndReturn(run func(db *gorm.DB, company *models.Company) error) *MockCompanyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCompanyRepository
func (_mock *MockCompanyRepository) FindByID(db *gorm.DB, id string) (*models.Company, error) {
	ret := _mock.Called(db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) (*models.Company, error)); ok {
		return returnFunc(db, id)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string) *models.Company); ok {
		r0 = returnFunc(db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = returnFunc(db, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompanyRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCompanyRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - db *gorm.DB
//   - id string
func (_e *MockCompanyRepository_Expecter) FindByID(db interface{}, id interface{}) *MockCompanyRepository_FindByID_Call {
	return &MockCompanyRepository_FindByID_Call{Call: _e.mock.On("FindByID", db, id)}
}

func (_c *MockCompanyRepository_FindByID_Call) Run(run func(db *gorm.DB, id string)) *MockCompanyRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompanyRepository_FindByID_Call) Return(company *models.Company, err error) *MockCompanyRepository_FindByID_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *MockCompanyRepository_FindByID_Call) RunAndReturn(run func(db *gorm.DB, id string) (*models.Company, error)) *MockCompanyRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
