// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/ijufumi/practice-202512/app/domain/models"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockInvoiceRepository creates a new instance of MockInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type MockInvoiceRepository struct {
	mock.Mock
}

type MockInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceRepository) EXPECT() *MockInvoiceRepository_Expecter {
	return &MockInvoiceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockInvoiceRepository
func (_mock *MockInvoiceRepository) Create(db *gorm.DB, invoice *models.Invoice) error {
	ret := _mock.Called(db, invoice)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *models.Invoice) error); ok {
		r0 = returnFunc(db, invoice)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInvoiceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInvoiceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - invoice *models.Invoice
func (_e *MockInvoiceRepository_Expecter) Create(db interface{}, invoice interface{}) *MockInvoiceRepository_Create_Call {
	return &MockInvoiceRepository_Create_Call{Call: _e.mock.On("Create", db, invoice)}
}

func (_c *MockInvoiceRepository_Create_Call) Run(run func(db *gorm.DB, invoice *models.Invoice)) *MockInvoiceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *models.Invoice
		if args[1] != nil {
			arg1 = args[1].(*models.Invoice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvoiceRepository_Create_Call) Return(err error) *MockInvoiceRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInvoiceRepository_Create_Call) RunAndReturn(run func(db *gorm.DB, invoice *models.Invoice) error) *MockInvoiceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPaymentDueDateRange provides a mock function for the type MockInvoiceRepository
func (_mock *MockInvoiceRepository) FindByPaymentDueDateRange(db *gorm.DB, startDate *time.Time, endDate *time.Time, offset int, limit int) ([]*models.Invoice, error) {
	ret := _mock.Called(db, startDate, endDate, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByPaymentDueDateRange")
	}

	var r0 []*models.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *time.Time, *time.Time, int, int) ([]*models.Invoice, error)); ok {
		return returnFunc(db, startDate, endDate, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *time.Time, *time.Time, int, int) []*models.Invoice); ok {
		r0 = returnFunc(db, startDate, endDate, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, *time.Time, *time.Time, int, int) error); ok {
		r1 = returnFunc(db, startDate, endDate, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInvoiceRepository_FindByPaymentDueDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPaymentDueDateRange'
type MockInvoiceRepository_FindByPaymentDueDateRange_Call struct {
	*mock.Call
}

// FindByPaymentDueDateRange is a helper method to define mock.On call
//   - db *gorm.DB
//   - startDate *time.Time
//   - endDate *time.Time
//   - offset int
//   - limit int
func (_e *MockInvoiceRepository_Expecter) FindByPaymentDueDateRange(db interface{}, startDate interface{}, endDate interface{}, offset interface{}, limit interface{}) *MockInvoiceRepository_FindByPaymentDueDateRange_Call {
	return &MockInvoiceRepository_FindByPaymentDueDateRange_Call{Call: _e.mock.On("FindByPaymentDueDateRange", db, startDate, endDate, offset, limit)}
}

func (_c *MockInvoiceRepository_FindByPaymentDueDateRange_Call) Run(run func(db *gorm.DB, startDate *time.Time, endDate *time.Time, offset int, limit int)) *MockInvoiceRepository_FindByPaymentDueDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInvoiceRepository_FindByPaymentDueDateRange_Call) Return(invoices []*models.Invoice, err error) *MockInvoiceRepository_FindByPaymentDueDateRange_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *MockInvoiceRepository_FindByPaymentDueDateRange_Call) RunAndReturn(run func(db *gorm.DB, startDate *time.Time, endDate *time.Time, offset int, limit int) ([]*models.Invoice, error)) *MockInvoiceRepository_FindByPaymentDueDateRange_Call {
	_c.Call.Return(run)
	return _c
}
