// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ijufumi/practice-202512/app/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInvoiceUsecase creates a new instance of MockInvoiceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceUsecase {
	mock := &MockInvoiceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInvoiceUsecase is an autogenerated mock type for the InvoiceUsecase type
type MockInvoiceUsecase struct {
	mock.Mock
}

type MockInvoiceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceUsecase) EXPECT() *MockInvoiceUsecase_Expecter {
	return &MockInvoiceUsecase_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function for the type MockInvoiceUsecase
func (_mock *MockInvoiceUsecase) CreateInvoice(ctx context.Context, clientID string, issueDate time.Time, paymentAmount int, paymentDueDate time.Time) (*models.Invoice, error) {
	ret := _mock.Called(ctx, clientID, issueDate, paymentAmount, paymentDueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 *models.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int, time.Time) (*models.Invoice, error)); ok {
		return returnFunc(ctx, clientID, issueDate, paymentAmount, paymentDueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int, time.Time) *models.Invoice); ok {
		r0 = returnFunc(ctx, clientID, issueDate, paymentAmount, paymentDueDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int, time.Time) error); ok {
		r1 = returnFunc(ctx, clientID, issueDate, paymentAmount, paymentDueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInvoiceUsecase_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockInvoiceUsecase_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - issueDate time.Time
//   - paymentAmount int
//   - paymentDueDate time.Time
func (_e *MockInvoiceUsecase_Expecter) CreateInvoice(ctx interface{}, clientID interface{}, issueDate interface{}, paymentAmount interface{}, paymentDueDate interface{}) *MockInvoiceUsecase_CreateInvoice_Call {
	return &MockInvoiceUsecase_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", ctx, clientID, issueDate, paymentAmount, paymentDueDate)}
}

func (_c *MockInvoiceUsecase_CreateInvoice_Call) Run(run func(ctx context.Context, clientID string, issueDate time.Time, paymentAmount int, paymentDueDate time.Time)) *MockInvoiceUsecase_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInvoiceUsecase_CreateInvoice_Call) Return(invoice *models.Invoice, err error) *MockInvoiceUsecase_CreateInvoice_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockInvoiceUsecase_CreateInvoice_Call) RunAndReturn(run func(ctx context.Context, clientID string, issueDate time.Time, paymentAmount int, paymentDueDate time.Time) (*models.Invoice, error)) *MockInvoiceUsecase_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoicesByPaymentDueDateRange provides a mock function for the type MockInvoiceUsecase
func (_mock *MockInvoiceUsecase) GetInvoicesByPaymentDueDateRange(ctx context.Context, startDate *time.Time, endDate *time.Time, offset int, limit int) ([]*models.Invoice, error) {
	ret := _mock.Called(ctx, startDate, endDate, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoicesByPaymentDueDateRange")
	}

	var r0 []*models.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) ([]*models.Invoice, error)); ok {
		return returnFunc(ctx, startDate, endDate, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) []*models.Invoice); ok {
		r0 = returnFunc(ctx, startDate, endDate, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, startDate, endDate, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoicesByPaymentDueDateRange'
type MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call struct {
	*mock.Call
}

// GetInvoicesByPaymentDueDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate *time.Time
//   - endDate *time.Time
//   - offset int
//   - limit int
func (_e *MockInvoiceUsecase_Expecter) GetInvoicesByPaymentDueDateRange(ctx interface{}, startDate interface{}, endDate interface{}, offset interface{}, limit interface{}) *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call {
	return &MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call{Call: _e.mock.On("GetInvoicesByPaymentDueDateRange", ctx, startDate, endDate, offset, limit)}
}

func (_c *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call) Run(run func(ctx context.Context, startDate *time.Time, endDate *time.Time, offset int, limit int)) *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call) Return(invoices []*models.Invoice, err error) *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call {
	_c.Call.Return(invoices, err)
	return _c
}

func (_c *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call) RunAndReturn(run func(ctx context.Context, startDate *time.Time, endDate *time.Time, offset int, limit int) ([]*models.Invoice, error)) *MockInvoiceUsecase_GetInvoicesByPaymentDueDateRange_Call {
	_c.Call.Return(run)
	return _c
}
